# -*- coding: utf-8 -*-
"""dummy_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p07pLz81Rw4m51GXCU2o7UbEh0Nc3DBE
"""

"""
Generate dummy data untuk project FMCG Sales & Distribution Analysis.
Menghasilkan 5 file CSV: dim_product, dim_outlet, dim_distributor, dim_calendar, fact_sales
"""

import csv
import random
from datetime import date, timedelta

random.seed(42)  # supaya hasil selalu sama tiap dijalankan

# ---------------------------------------------------------
# 1. dim_product
# ---------------------------------------------------------
categories = {
    "Personal Care": ["Sabun Mandi", "Sampo", "Pasta Gigi", "Deodoran", "Lotion"],
    "Food & Beverage": ["Kecap", "Susu Bubuk", "Teh Celup", "Mi Instan", "Minyak Goreng"],
    "Household": ["Deterjen", "Pewangi Pakaian", "Sabun Cuci Piring", "Pembersih Lantai"],
}
brands = ["Nuansa", "Ceria", "Segar Alam", "Rumahku", "Harmoni"]

product_rows = []
product_id = 1
for category, subcats in categories.items():
    for sub in subcats:
        for brand in random.sample(brands, k=2):  # tiap sub-kategori punya 2 varian brand
            product_rows.append({
                "product_id": product_id,
                "product_name": f"{brand} {sub}",
                "category": category,
                "sub_category": sub,
                "brand": brand,
                "unit_price": random.randint(3, 50) * 1000,
            })
            product_id += 1

with open("dim_product.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=product_rows[0].keys())
    writer.writeheader()
    writer.writerows(product_rows)

n_products = len(product_rows)

# ---------------------------------------------------------
# 2. dim_outlet
# ---------------------------------------------------------
regions = ["Jakarta", "Jawa Barat", "Jawa Tengah", "Jawa Timur",
           "Sumatera Utara", "Sumatera Selatan", "Kalimantan", "Sulawesi"]
region_cities = {
    "Jakarta": ["Jakarta Pusat", "Jakarta Selatan", "Jakarta Timur"],
    "Jawa Barat": ["Bandung", "Bekasi", "Bogor"],
    "Jawa Tengah": ["Semarang", "Solo", "Magelang"],
    "Jawa Timur": ["Surabaya", "Malang", "Kediri"],
    "Sumatera Utara": ["Medan", "Binjai"],
    "Sumatera Selatan": ["Palembang", "Lubuklinggau"],
    "Kalimantan": ["Balikpapan", "Banjarmasin"],
    "Sulawesi": ["Makassar", "Manado"],
}
outlet_types = ["Modern Trade", "General Trade"]
outlet_name_prefix = ["Toko", "Minimarket", "Warung", "Swalayan"]

outlet_rows = []
n_outlets = 120
for oid in range(1, n_outlets + 1):
    region = random.choice(regions)
    city = random.choice(region_cities[region])
    outlet_rows.append({
        "outlet_id": oid,
        "outlet_name": f"{random.choice(outlet_name_prefix)} {city} {oid}",
        "outlet_type": random.choice(outlet_types),
        "region": region,
        "city": city,
    })

with open("dim_outlet.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=outlet_rows[0].keys())
    writer.writeheader()
    writer.writerows(outlet_rows)

# ---------------------------------------------------------
# 3. dim_distributor
# ---------------------------------------------------------
distributor_rows = []
n_distributors = 12
for did in range(1, n_distributors + 1):
    region = random.choice(regions)
    distributor_rows.append({
        "distributor_id": did,
        "distributor_name": f"PT Distribusi {region.replace(' ', '')} {did}",
        "region": region,
    })

with open("dim_distributor.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=distributor_rows[0].keys())
    writer.writeheader()
    writer.writerows(distributor_rows)

# ---------------------------------------------------------
# 4. dim_calendar
# ---------------------------------------------------------
start_date = date(2025, 1, 1)
end_date = date(2025, 12, 31)
ramadan_start = date(2025, 3, 1)   # perkiraan Ramadan 2025
ramadan_end = date(2025, 3, 30)

calendar_rows = []
d = start_date
while d <= end_date:
    calendar_rows.append({
        "date": d.isoformat(),
        "month": d.strftime("%B"),
        "quarter": (d.month - 1) // 3 + 1,
        "year": d.year,
        "is_ramadan_period": ramadan_start <= d <= ramadan_end,
    })
    d += timedelta(days=1)

with open("dim_calendar.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=calendar_rows[0].keys())
    writer.writeheader()
    writer.writerows(calendar_rows)

all_dates = [row["date"] for row in calendar_rows]
ramadan_dates = {row["date"] for row in calendar_rows if row["is_ramadan_period"]}

# ---------------------------------------------------------
# 5. fact_sales
# ---------------------------------------------------------
fact_rows = []
n_transactions = 4000
for tid in range(1, n_transactions + 1):
    tdate = random.choice(all_dates)
    pid = random.randint(1, n_products)
    oid = random.randint(1, n_outlets)
    did = random.randint(1, n_distributors)

    # sedikit lonjakan penjualan saat ramadan, untuk simulasi pola musiman
    seasonal_multiplier = 1.4 if tdate in ramadan_dates else 1.0

    qty = int(random.randint(1, 150) * seasonal_multiplier)
    sell_in = int(random.randint(50000, 3000000) * seasonal_multiplier)
    # sell_out sedikit lebih rendah dari sell_in (gap wajar, indikasi stok belum terjual semua)
    sell_out = int(sell_in * random.uniform(0.75, 0.98))
    stock_available = random.randint(0, 500)

    fact_rows.append({
        "transaction_id": tid,
        "date": tdate,
        "product_id": pid,
        "outlet_id": oid,
        "distributor_id": did,
        "qty_sold": qty,
        "sell_in_value": sell_in,
        "sell_out_value": sell_out,
        "stock_available": stock_available,
    })

with open("fact_sales.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fact_rows[0].keys())
    writer.writeheader()
    writer.writerows(fact_rows)

print(f"Selesai. dim_product: {n_products} baris, dim_outlet: {n_outlets} baris, "
      f"dim_distributor: {n_distributors} baris, dim_calendar: {len(calendar_rows)} baris, "
      f"fact_sales: {n_transactions} baris")